<?php

namespace Proyecto\CorrespondenciaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CorrespondenciaRecibidaInternaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Proyecto\CorrespondenciaBundle\Controller\CorrespondenciaRecibidaInternaController();
        return $instance;
    }
}
