<?php

namespace Proyecto\UsuarioBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UsuarioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Proyecto\UsuarioBundle\Controller\UsuarioController();
        return $instance;
    }
}
