parameters:
#    reporte.example.class: Proyecto\ReporteBundle\Example

services:
#    reporte.example:
#        class: %reporte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
