<?php

namespace Proxies\__CG__\Proyecto\UsuarioBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Usuario extends \Proyecto\UsuarioBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUse_code()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["use_code"];
        }
        $this->__load();
        return parent::getUse_code();
    }

    public function setUse_code($use_code)
    {
        $this->__load();
        return parent::setUse_code($use_code);
    }

    public function getUse_name()
    {
        $this->__load();
        return parent::getUse_name();
    }

    public function setUse_name($use_name)
    {
        $this->__load();
        return parent::setUse_name($use_name);
    }

    public function getUse_dependencia()
    {
        $this->__load();
        return parent::getUse_dependencia();
    }

    public function setUse_dependencia($use_dependencia)
    {
        $this->__load();
        return parent::setUse_dependencia($use_dependencia);
    }

    public function getUse_phone()
    {
        $this->__load();
        return parent::getUse_phone();
    }

    public function setUse_phone($use_phone)
    {
        $this->__load();
        return parent::setUse_phone($use_phone);
    }

    public function getUse_email()
    {
        $this->__load();
        return parent::getUse_email();
    }

    public function setUse_email($use_email)
    {
        $this->__load();
        return parent::setUse_email($use_email);
    }

    public function getUse_login()
    {
        $this->__load();
        return parent::getUse_login();
    }

    public function setUse_login($use_login)
    {
        $this->__load();
        return parent::setUse_login($use_login);
    }

    public function getUse_password()
    {
        $this->__load();
        return parent::getUse_password();
    }

    public function setUse_password($use_password)
    {
        $this->__load();
        return parent::setUse_password($use_password);
    }

    public function getUse_original()
    {
        $this->__load();
        return parent::getUse_original();
    }

    public function setUse_original($use_original)
    {
        $this->__load();
        return parent::setUse_original($use_original);
    }

    public function getUse_rename()
    {
        $this->__load();
        return parent::getUse_rename();
    }

    public function setUse_rename($use_rename)
    {
        $this->__load();
        return parent::setUse_rename($use_rename);
    }

    public function getUse_status()
    {
        $this->__load();
        return parent::getUse_status();
    }

    public function setUse_status($use_status)
    {
        $this->__load();
        return parent::setUse_status($use_status);
    }

    public function getUse_type()
    {
        $this->__load();
        return parent::getUse_type();
    }

    public function setUse_type($use_type)
    {
        $this->__load();
        return parent::setUse_type($use_type);
    }

    public function getUse_date_create()
    {
        $this->__load();
        return parent::getUse_date_create();
    }

    public function setUse_date_create($use_date_create)
    {
        $this->__load();
        return parent::setUse_date_create($use_date_create);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'use_code', 'use_name', 'use_dependencia', 'use_phone', 'use_email', 'use_login', 'use_password', 'use_original', 'use_rename', 'use_status', 'use_type', 'use_date_create');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}